export type ThemeMode = 'light' | 'dark'

export type CssCustomPropertyMap = Readonly<Record<`--${string}`, string>>

export const transformotionLogoAssets = {
  transparent: '/images/brand/transformotion-logo-transparent.png',
  white: '/images/brand/transformotion-logo-white.jpg',
  navy: '/images/brand/transformotion-logo-navy.png',
} as const

export const typographyTokens = {
  display: {
    family: 'Oswald',
    cssVariable: '--font-oswald',
    usage: 'app names, page headings, major section headings, important card and section titles',
  },
  ui: {
    family: 'Inter',
    cssVariable: '--font-inter',
    usage: 'body, UI, navigation, buttons, forms, tables, badges, and stats',
  },
  numeric: {
    family: 'Inter',
    cssVariable: '--font-inter',
    feature: 'tabular-nums',
    usage: 'financial and statistical values',
  },
  mono: {
    family: 'Geist Mono',
    cssVariable: '--font-geist-mono',
    usage: 'code-like and technical values',
  },
} as const

export const brandPalette = {
  navy: {
    light: '#23476B',
    dark: '#4F759C',
  },
  navyForeground: {
    light: '#F9FAFB',
    dark: '#F6F9FB',
  },
  teal: {
    light: '#33C1C5',
    dark: '#33C1C5',
  },
  tealForeground: {
    light: '#0E2339',
    dark: '#071728',
  },
  gold: {
    light: '#DCA331',
    dark: '#E2AE43',
  },
  brandBand: {
    light: '#23476B',
    dark: '#FFFFFF',
  },
} as const

export const statusTokens = {
  success: {
    light: '#1E8E5A',
    dark: '#22C87A',
  },
  signalGreen: {
    light: '#1E8E5A',
    dark: '#22C87A',
  },
  warning: {
    light: '#B7791F',
    dark: '#E2AE43',
  },
  destructive: {
    light: '#E7000B',
    dark: '#F14D4C',
  },
  info: {
    light: '#23476B',
    dark: '#5B8ABB',
  },
} as const

export const chartColorTokens = {
  chart1: {
    light: '#23476B',
    dark: '#5B8ABB',
  },
  chart2: {
    light: '#33C1C5',
    dark: '#33C1C5',
  },
  chart3: {
    light: '#8F9AA4',
    dark: '#95A0AB',
  },
  chart4: {
    light: '#587494',
    dark: '#45668A',
  },
  chart5: {
    light: '#DCA331',
    dark: '#E2AE43',
  },
  grid: {
    light: 'rgba(29,47,68,.08)',
    dark: 'rgba(255,255,255,.06)',
  },
} as const

export const budgetTrackerCategoryColorTokens = {
  navy: '#23476B',
  teal: '#33C1C5',
  steelBlue: '#587494',
  tealGreen: '#2F9E8F',
  gold: '#DCA331',
  bronze: '#B7791F',
  slate: '#8F9AA4',
  signalGreen: '#1E8E5A',
} as const

export const signalGreenTokens = statusTokens.signalGreen

export const radiusTokens = {
  base: '0.625rem',
  small: 'calc(var(--radius) - 4px)',
  medium: 'calc(var(--radius) - 2px)',
  large: 'var(--radius)',
  extraLarge: 'calc(var(--radius) + 4px)',
} as const

export const shadowTokens = {} as const

export const semanticThemeTokens = {
  light: {
    background: '#F4F7F9',
    foreground: '#1D2F44',
    card: '#FFFFFF',
    cardForeground: '#1D2F44',
    popover: '#FFFFFF',
    popoverForeground: '#1D2F44',
    primary: '#33C1C5',
    primaryForeground: '#0E2339',
    secondary: '#EBEFF2',
    secondaryForeground: '#23476B',
    muted: '#EBEFF2',
    mutedForeground: '#677380',
    accent: '#33C1C5',
    accentForeground: '#0E2339',
    destructive: '#E7000B',
    border: '#DDE2E6',
    input: '#DDE2E6',
    ring: '#33C1C5',
    sidebar: '#23476B',
    sidebarForeground: '#F9FAFB',
    sidebarPrimary: '#33C1C5',
    sidebarPrimaryForeground: '#0E2339',
    sidebarAccent: '#33C1C5',
    sidebarAccentForeground: '#0E2339',
    sidebarBorder: 'rgba(255,255,255,.18)',
    sidebarRing: '#33C1C5',
  },
  dark: {
    background: '#0C141D',
    foreground: '#EBEFF2',
    card: '#151F2A',
    cardForeground: '#EBEFF2',
    popover: '#151F2A',
    popoverForeground: '#EBEFF2',
    primary: '#33C1C5',
    primaryForeground: '#071728',
    secondary: '#202A36',
    secondaryForeground: '#EBEFF2',
    muted: '#202A36',
    mutedForeground: '#95A0AB',
    accent: '#33C1C5',
    accentForeground: '#071728',
    destructive: '#F14D4C',
    border: 'rgba(255,255,255,.12)',
    input: 'rgba(255,255,255,.16)',
    ring: '#33C1C5',
    sidebar: '#080F17',
    sidebarForeground: '#EBEFF2',
    sidebarPrimary: '#33C1C5',
    sidebarPrimaryForeground: '#071728',
    sidebarAccent: '#33C1C5',
    sidebarAccentForeground: '#071728',
    sidebarBorder: 'rgba(255,255,255,.12)',
    sidebarRing: '#33C1C5',
  },
} as const

export const brandThemeTokens = {
  light: {
    navy: brandPalette.navy.light,
    navyForeground: brandPalette.navyForeground.light,
    teal: brandPalette.teal.light,
    tealForeground: brandPalette.tealForeground.light,
    gold: brandPalette.gold.light,
    brandBand: brandPalette.brandBand.light,
  },
  dark: {
    navy: brandPalette.navy.dark,
    navyForeground: brandPalette.navyForeground.dark,
    teal: brandPalette.teal.dark,
    tealForeground: brandPalette.tealForeground.dark,
    gold: brandPalette.gold.dark,
    brandBand: brandPalette.brandBand.dark,
  },
} as const

export const themeCssVariableMaps = {
  light: {
    '--background': semanticThemeTokens.light.background,
    '--foreground': semanticThemeTokens.light.foreground,
    '--card': semanticThemeTokens.light.card,
    '--card-foreground': semanticThemeTokens.light.cardForeground,
    '--popover': semanticThemeTokens.light.popover,
    '--popover-foreground': semanticThemeTokens.light.popoverForeground,
    '--primary': semanticThemeTokens.light.primary,
    '--primary-foreground': semanticThemeTokens.light.primaryForeground,
    '--secondary': semanticThemeTokens.light.secondary,
    '--secondary-foreground': semanticThemeTokens.light.secondaryForeground,
    '--muted': semanticThemeTokens.light.muted,
    '--muted-foreground': semanticThemeTokens.light.mutedForeground,
    '--accent': semanticThemeTokens.light.accent,
    '--accent-foreground': semanticThemeTokens.light.accentForeground,
    '--destructive': semanticThemeTokens.light.destructive,
    '--border': semanticThemeTokens.light.border,
    '--input': semanticThemeTokens.light.input,
    '--ring': semanticThemeTokens.light.ring,
    '--chart-1': chartColorTokens.chart1.light,
    '--chart-2': chartColorTokens.chart2.light,
    '--chart-3': chartColorTokens.chart3.light,
    '--chart-4': chartColorTokens.chart4.light,
    '--chart-5': chartColorTokens.chart5.light,
    '--chart-grid': chartColorTokens.grid.light,
    '--sidebar': semanticThemeTokens.light.sidebar,
    '--sidebar-foreground': semanticThemeTokens.light.sidebarForeground,
    '--sidebar-primary': semanticThemeTokens.light.sidebarPrimary,
    '--sidebar-primary-foreground': semanticThemeTokens.light.sidebarPrimaryForeground,
    '--sidebar-accent': semanticThemeTokens.light.sidebarAccent,
    '--sidebar-accent-foreground': semanticThemeTokens.light.sidebarAccentForeground,
    '--sidebar-border': semanticThemeTokens.light.sidebarBorder,
    '--sidebar-ring': semanticThemeTokens.light.sidebarRing,
    '--brand-navy': brandThemeTokens.light.navy,
    '--brand-navy-foreground': brandThemeTokens.light.navyForeground,
    '--brand-teal': brandThemeTokens.light.teal,
    '--brand-teal-foreground': brandThemeTokens.light.tealForeground,
    '--brand-gold': brandThemeTokens.light.gold,
    '--brand-band': brandThemeTokens.light.brandBand,
    '--status-success': statusTokens.success.light,
    '--status-warning': statusTokens.warning.light,
    '--status-destructive': statusTokens.destructive.light,
    '--status-info': statusTokens.info.light,
    '--radius': radiusTokens.base,
  },
  dark: {
    '--background': semanticThemeTokens.dark.background,
    '--foreground': semanticThemeTokens.dark.foreground,
    '--card': semanticThemeTokens.dark.card,
    '--card-foreground': semanticThemeTokens.dark.cardForeground,
    '--popover': semanticThemeTokens.dark.popover,
    '--popover-foreground': semanticThemeTokens.dark.popoverForeground,
    '--primary': semanticThemeTokens.dark.primary,
    '--primary-foreground': semanticThemeTokens.dark.primaryForeground,
    '--secondary': semanticThemeTokens.dark.secondary,
    '--secondary-foreground': semanticThemeTokens.dark.secondaryForeground,
    '--muted': semanticThemeTokens.dark.muted,
    '--muted-foreground': semanticThemeTokens.dark.mutedForeground,
    '--accent': semanticThemeTokens.dark.accent,
    '--accent-foreground': semanticThemeTokens.dark.accentForeground,
    '--destructive': semanticThemeTokens.dark.destructive,
    '--border': semanticThemeTokens.dark.border,
    '--input': semanticThemeTokens.dark.input,
    '--ring': semanticThemeTokens.dark.ring,
    '--chart-1': chartColorTokens.chart1.dark,
    '--chart-2': chartColorTokens.chart2.dark,
    '--chart-3': chartColorTokens.chart3.dark,
    '--chart-4': chartColorTokens.chart4.dark,
    '--chart-5': chartColorTokens.chart5.dark,
    '--chart-grid': chartColorTokens.grid.dark,
    '--sidebar': semanticThemeTokens.dark.sidebar,
    '--sidebar-foreground': semanticThemeTokens.dark.sidebarForeground,
    '--sidebar-primary': semanticThemeTokens.dark.sidebarPrimary,
    '--sidebar-primary-foreground': semanticThemeTokens.dark.sidebarPrimaryForeground,
    '--sidebar-accent': semanticThemeTokens.dark.sidebarAccent,
    '--sidebar-accent-foreground': semanticThemeTokens.dark.sidebarAccentForeground,
    '--sidebar-border': semanticThemeTokens.dark.sidebarBorder,
    '--sidebar-ring': semanticThemeTokens.dark.sidebarRing,
    '--brand-navy': brandThemeTokens.dark.navy,
    '--brand-navy-foreground': brandThemeTokens.dark.navyForeground,
    '--brand-teal': brandThemeTokens.dark.teal,
    '--brand-teal-foreground': brandThemeTokens.dark.tealForeground,
    '--brand-gold': brandThemeTokens.dark.gold,
    '--brand-band': brandThemeTokens.dark.brandBand,
    '--status-success': statusTokens.success.dark,
    '--status-warning': statusTokens.warning.dark,
    '--status-destructive': statusTokens.destructive.dark,
    '--status-info': statusTokens.info.dark,
    '--radius': radiusTokens.base,
  },
} as const satisfies Record<ThemeMode, CssCustomPropertyMap>

export const tailwindThemeInlineVariableMap = {
  '--color-background': 'var(--background)',
  '--color-foreground': 'var(--foreground)',
  '--color-card': 'var(--card)',
  '--color-card-foreground': 'var(--card-foreground)',
  '--color-popover': 'var(--popover)',
  '--color-popover-foreground': 'var(--popover-foreground)',
  '--color-primary': 'var(--primary)',
  '--color-primary-foreground': 'var(--primary-foreground)',
  '--color-secondary': 'var(--secondary)',
  '--color-secondary-foreground': 'var(--secondary-foreground)',
  '--color-muted': 'var(--muted)',
  '--color-muted-foreground': 'var(--muted-foreground)',
  '--color-accent': 'var(--accent)',
  '--color-accent-foreground': 'var(--accent-foreground)',
  '--color-destructive': 'var(--destructive)',
  '--color-border': 'var(--border)',
  '--color-input': 'var(--input)',
  '--color-ring': 'var(--ring)',
  '--color-chart-1': 'var(--chart-1)',
  '--color-chart-2': 'var(--chart-2)',
  '--color-chart-3': 'var(--chart-3)',
  '--color-chart-4': 'var(--chart-4)',
  '--color-chart-5': 'var(--chart-5)',
  '--color-sidebar': 'var(--sidebar)',
  '--color-sidebar-foreground': 'var(--sidebar-foreground)',
  '--color-sidebar-primary': 'var(--sidebar-primary)',
  '--color-sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
  '--color-sidebar-accent': 'var(--sidebar-accent)',
  '--color-sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
  '--color-sidebar-border': 'var(--sidebar-border)',
  '--color-sidebar-ring': 'var(--sidebar-ring)',
  '--color-brand-navy': 'var(--brand-navy)',
  '--color-brand-navy-foreground': 'var(--brand-navy-foreground)',
  '--color-brand-teal': 'var(--brand-teal)',
  '--color-brand-teal-foreground': 'var(--brand-teal-foreground)',
  '--color-brand-gold': 'var(--brand-gold)',
  '--color-brand-band': 'var(--brand-band)',
  '--color-status-success': 'var(--status-success)',
  '--color-status-warning': 'var(--status-warning)',
  '--color-status-destructive': 'var(--status-destructive)',
  '--color-status-info': 'var(--status-info)',
  '--font-sans': 'var(--font-inter)',
  '--font-mono': 'var(--font-geist-mono)',
  '--font-display': 'var(--font-oswald)',
  '--radius-sm': radiusTokens.small,
  '--radius-md': radiusTokens.medium,
  '--radius-lg': radiusTokens.large,
  '--radius-xl': radiusTokens.extraLarge,
} as const satisfies CssCustomPropertyMap
