packages:
  - 'apps/*'
  - 'apps/stock-analyser/functions/*'
  - 'apps/budget-tracker/functions/*'
  - 'packages/*'
  - 'packages/ui/*'
  - 'platform/functions/*'
  - 'platform/functions/auth/*'
  - 'infrastructure'
  - 'migration-utilities/infrastructure'
  - 'migration-utilities/**'
